server:
  port: ${CAPort:${PORT:5001}}
logging:
  config: file:config/logback.xml

spring:
  application:
    name: bms-server
  config:
    import:
      - "file:config/application-redis.yml"

#跨域配置
easyfk:
  config:
    web:
      cors:
        open: true